export default {
  eth_account: '#eth_accounts',
  claim_button: '#claim_button',
  gas_price_input: '#gas_price',
  claim_eth_input: '#claim_value',
  logging_element: '#eth_log',
  tokens_left_element: '#tokensLeft',
  tokens_bought_element: '#tokensBought',
  presale_over_element: '#presale-over',
  token_price_element: '#tokenPrice',
  chart_element: 'chartdiv',
  bar_element: '.progressbar-container',
  token_usd_price: '#discTokenPrice',
  ribbon_token_price: '#ribTokenPrice',
  ribbon_token_dollar_price: '#ribDolPrice',
  ribbon_token_btc_price: '#ribSupBtcPrice',
  ribbon_ether_btc_price: '#ribEthBtcPrice',
};
